### ISSUE TITLE
how to run a Private Network

### ISSUE THREAD

**Issue by zychappy** [fractalplatform/fractal#134]
the wiki is still a blank

**Comment by suoyc** [comment]
Development environment

Go version:

go1.9.2 and higher
Currently supports the following operating systems:

Ubuntu 16.04
Ubuntu 18.04
MacOS Darwin 10.12 and higher
Building the source

To download all of the code in $GOPATH/src/github.com/fractalplatform:

git clone https://github.com/fractalplatform/fractal

Enter the project directory

cd fractal

To build the full suite of utilities:

make all

the ft and fkey in ./build/bin

Start node

On current project directory

./build/bin/ft --genesis=./build/genesis.json  --miner_start

 ./build/bin/ft -help get more commands
