### ISSUE TITLE
Debugging errors properly

### ISSUE THREAD

**Issue by snwfdhmp** [fractalplatform/fractal#38]
### You should not panic(err)

https://github.com/fractalplatform/fractal/blob/1d8e1868b9daccac6ffc5fa41904654b51476c96/asset/asset.go#L153-L155

Hey dude,

Just a friendly advice. You should not panic(err). You’d rather use [a package like this](https://github.com/snwfdhmp/errlog) for debugging your errors. Debug your code with :

1. Clear stack trace
2. Failing func call highlighting

<img width="999" alt="example" src="https://user-images.githubusercontent.com/23099246/53098953-11310c80-3525-11e9-8f6f-302791743cdf.png">

It’s way more easier then to debug.

Real better than panic-ing (in most case). You can still force exit if you need it.

I would be happy to get your feedbacks.

**Comment by findbug2019** [comment]
Thank you for your advice.
