### ISSUE TITLE
[master/dev]Exceptionally close the node, the node can not continue to synchronize data

### ISSUE THREAD

**Issue by suoyc** [fractalplatform/fractal#406]
DEBUG[07-25|11:33:41.844] downloader statusTD x                    Local=53557276256 Number=19561 R=57070210640 Number=20839
DEBUG[07-25|11:33:41.844] downloader findAncestor                  headNumber=19561 preAncestor=0 irreversibleNumber=20306
WARN [07-25|11:33:41.844] ancestor err                             err="can not find ancestor after irreversibleNumber:20306" errid:=3
WARN [07-25|11:33:41.844] Disconnect because ancestor not find:    station:=ecc702621e254cc2
DEBUG[07-25|11:33:41.844] multiplexDownload end 
INFO [07-25|11:33:41.844] Add bad node                             node="&{node:0xc43029f7a0 endtime:1564025681}"
INFO [07-25|11:33:41.845] Removing p2p peer                        id=ecc702621e254cc2 conn=dyndial duration=3.021ms peers=10 req=false err="peer was added in the balcklist at least 1 minute"

**Comment by erickyan86** [comment]
resolved
