### ISSUE TITLE
the genesis bootnodes' ip addresses are invalid

### ISSUE THREAD

**Issue by GeekDaiDao** [fractalplatform/fractal#426]
Excuse me , there were something wrong when i set up a node. During the process of starting a node, everything was fine except  a warn"genesis bootnodes prased failed"and detail information just showed "invalid IP address". So , if you were just change the ip address in he "genesis.json" and "testnet.json"? The addresses you gave in theses two documents were all unable to connect, thus I can not find any other nodes.
It will be greatly appreciated if you can reply me soon. Thx!

**Comment by peekpi** [comment]
There are three bootnodes in genesis.json, but only the first bootnode is valid, so it may take a long time to join the P2P networking. The other bootnodes in genesis is now invalid and will used in the future.

**Comment by GeekDaiDao** [comment]
Thanks 4 your  answer. But there is still a question unsolved. Though the error"invalid" has been solved after i deleted 2 bootnodes for future, I can not connect with any other nodes in "testnet"yet. Then I used "ftfinder" for searching nodes in the network.,but unfortunately nothing was founded. I just checked the command line options that "nodes with different P2P_id can not connect with each other". So if the command you posted in Testnetwork"**./build/bin/ft --genesis=./build/testnet.json --p2p_id 2**" has changed the p2p_id? Or do you agree discussing this issue in QQ? i just find that your email is set with it.

**Comment by peekpi** [comment]
We have a telegram group:
Telegram: [t.me/FractalOfficial](https://t.me/FractalOfficial)
