### ISSUE TITLE
when I run a Private Network, it shows ERROR

### ISSUE THREAD

**Issue by jiebanghan** [fractalplatform/fractal#518]
when I run a private networks  as https://github.com/fractalplatform/fractal/issues/134.
But after I runed ./build/bin/ft --genesis=./build/genesis.json --miner_start
it shows below
```
INFO [10-18|15:35:32.046] No config file , use default configuration. 
INFO [10-18|15:35:32.046] fractal node                             version=0.0.30+commit.v0.0.30-26-g2c95589+date.2019-10-18
INFO [10-18|15:35:32.046] Reading read genesis file                path=./build/genesis.json
WARN [10-18|15:35:32.072] genesis bootnodes parse failed           err="invalid IP address" node=fnode://9d18e8f043a1d2c06d87506cd968410a24db7cbca3c152e75a9e3850b9b737ec85da66c271ac9f703c61e5367d8922d39e145313ff7cb379d9c8d682a15f60dc@boot2.m.ft.im:30000
WARN [10-18|15:35:32.075] genesis bootnodes parse failed           err="invalid IP address" node=fnode://6629defca0f82ede9cb30d40a2ec6e8c56f51080ad49e9099eb960bed63829ee259bdec6c357d2b43ebdb621b1a54da268d35088bd9db80245936a58c299e1e6@boot3.m.ft.im:30000
INFO [10-18|15:35:32.079] Allocated cache and file handles         database=/root/.ft_ledger/ft/chaindata cache=768 handles=512
WARN [10-18|15:35:32.096] genesis bootnodes parse failed           err="invalid IP address" node=fnode://9d18e8f043a1d2c06d87506cd968410a24db7cbca3c152e75a9e3850b9b737ec85da66c271ac9f703c61e5367d8922d39e145313ff7cb379d9c8d682a15f60dc@boot2.m.ft.im:30000
WARN [10-18|15:35:32.099] genesis bootnodes parse failed           err="invalid IP address" node=fnode://6629defca0f82ede9cb30d40a2ec6e8c56f51080ad49e9099eb960bed63829ee259bdec6c357d2b43ebdb621b1a54da268d35088bd9db80245936a58c299e1e6@boot3.m.ft.im:30000
ERROR[10-18|15:35:32.102] ft start node failed.                    err="database already contains an incompatible genesis block (have fff77195a34bae2cbe56990436ef0ae4f41f1a466a1a7943f7040ecdd19eceba, new 3b7172d970b3309c11aabdfadf50a81a80649d57f4c1c47b7eb62328eb9e0f48)"
```

so how to solve the problem above ,thanks.

**Comment by jiebanghan** [comment]
It seems that the db has already stores a genesis block.so I can't store a new genesis block.But how to solve it?

**Comment by JacobDenver007** [comment]
1、you might run a node before, so please remove the database first: rm -rf /root/.ft_ledger/
2、by the way, if you want to run a private node, you should not use genesis.json, because it will make your node a mainnet node, so you should run like this: ./build/bin/ft --miner_start
3、the default private key of fractal.founder is 289c2857d4598e37fb9647507e47a309d6133539bf21a8b9cb6df88fd5232032

**Comment by jiebanghan** [comment]
Thank you , it did works as you said.

**Comment by jiebanghan** [comment]
hi, there is a new question, after  some days I rerun the command
`./build/bin/ft --miner_start` as @JacobDenver007 said. but it  show me the result below:

`WARN [10-28|10:59:39.000] failed to mint the block                 timestamp=1572231579000000000 err="system account take over" candidate=fractal.founder` many times
what is the reason? and how to solve it？ thank you .

**Comment by JacobDenver007** [comment]
when you stop your node over some time, and you start the node again, it will happen, please use commands `./build/bin/ft -i /root/.ft_ledger/ft.ipc miner stop` and `./build/bin/ft -i /root/.ft_ledger/ft.ipc miner force`

**Comment by jiebanghan** [comment]
ok ,thank you .

**Comment by jiebanghan** [comment]
```
[Mon Oct 28 11:20:09]#./ft -i /root/.ft_ledger/ft.ipc miner stop
ERROR 2019/10/28 11:20:26 dial unix /root/.ft_ledger/ft.ipc: connect: no such file or directory
[Mon Oct 28 11:20:26]#ls /root/.ft_ledger/
ft  nodedb
```
@JacobDenver007 ,please help  me.
thank you a lot
when I running the command  ./build/bin/ft --miner_start , there is the ft.ipc , but when I stop mine , ft.ipc vanish.

**Comment by JacobDenver007** [comment]
1、if your node is stopped, you should start node first, then use my commands
2、`ft.ipc` this file is located at your node's data direction, please check your datadir, maybe you can search this file after you start your node, see https://github.com/fractalplatform/fractal/wiki/Command-Line-Options#startpure

**Comment by jiebanghan** [comment]
OK, Thank you so much .

**Comment by jiebanghan** [comment]
Yes, it does works. thank you @JacobDenver007

**Comment by jiebanghan** [comment]
hi, @JacobDenver007, when I am in private networks, there is no vote for candidate, is it right? the only candidate is the "fractal.founder"? Of course , there is noly one node in the private networks.
so how should the nodes can vote candidates? 
Another question is that : is dpos is ft's consensus algorithm ?
thank you very much。

**Comment by JacobDenver007** [comment]
join our telegram: [t.me/FractalOfficial](url)

**Comment by jiebanghan** [comment]
Firstly , I give my thank to @JacobDenver007 , but I seem can't join the telegram technically. So would you please tell me the solution here? thank you .

**Comment by JacobDenver007** [comment]
1、you should change your genesis.json, see https://github.com/fractalplatform/fractal/wiki/%E5%88%9B%E4%B8%96%E6%96%87%E4%BB%B6genesis.json%E8%AF%B4%E6%98%8E
especially you should change `candidateScheduleSize ` and `backupScheduleSize`
2、you have to start at least candidateScheduleSize+backupScheduleSize nodes
3、you should create some accounts first to use as miner
4、for each node, you should set its own miner, using this command https://github.com/fractalplatform/fractal/wiki/Command-Line-Options#setcoinbase
5、issue the candidates, see https://github.com/fractalplatform/fractal/wiki/%E4%BA%A4%E6%98%93payload%E6%9E%84%E9%80%A0#%E6%B3%A8%E5%86%8C%E5%80%99%E9%80%89%E8%80%85
6、vote

**Comment by jiebanghan** [comment]
Thank you very much.Thank you very much.Thank you very much. @JacobDenver007

**Comment by jiebanghan** [comment]
when I modify the genesis.json, then I run 
`#./bin/ft --genesis=./genesis.json --miner_start`
it shows : 
```
INFO [11-05|15:32:16.177] WebSocket endpoint opened                url=ws://127.0.0.1:8546
WARN [11-05|15:32:18.001] failed to mint the block                 timestamp=1572939138000000000 err="illegal candidate pubkey" candidate=fractal.founder
WARN [11-05|15:32:21.001] failed to mint the block                 timestamp=1572939141000000000 err="illegal candidate pubkey" candidate=fractal.founder
WARN [11-05|15:32:24.000] failed to mint the block                 timestamp=1572939144000000000 err="illegal candidate pubkey" candidate=fractal.founder
WARN [11-05|15:32:27.002] failed to mint the block                 timestamp=1572939147000000000 err="illegal candidate pubkey" candidate=fractal.founder
```
I found message concerned  below
https://github.com/fractalplatform/fractal/wiki/%E5%A6%82%E4%BD%95%E6%90%AD%E5%BB%BAFractal%E7%A7%81%E6%9C%89%E7%BD%91%E7%BB%9C
2:修改 genesis.json 文件中的矿工配置
默认出块账号是 fractal.admin,我们需要将其对应的公钥修改为我们自己的公钥（在这之前需要有自己的公私钥对）；

>cd build
>vim genesis.json
找到文件中的 fractal.admin，将其对应的 pubKey 修改为自己的公钥

问题1， 我没在genesis.json中找到fractal.admin，只找到了"fractal.founder"，是不是"fractal.founder"修改公钥 即可?然后修改这个公钥？
问题2， >./ft miner -i ./data/ft.ipc setcoinbase "fractal.admin" privateKey.txt
>tail -f nohup.out  // 此时能看到开始正常出块了
privateKey.txt 里存放的是私钥，注意私钥不需要带 0x 前缀，此命令执行完后记得删除 privateKey.txt 这个文件，以防私钥泄露

这个privateKey.txt,是不是我自己在文件里面写一个私钥？应该以什么规则写这个私钥？是自己随意写个私钥吗？
谢谢。

**Comment by JacobDenver007** [comment]
1、使用fractal.founder
2、./ft miner -i ./data/ft.ipc setcoinbase "fractal.founder" privateKey.txt, 可以使用自己生成的公私钥对，记得要修改genesis.json里面fractal.founder的公钥，和privateKey.txt里的私钥匹配即可（可以使用下面这个公私钥对，私钥289c2857d4598e37fb9647507e47a309d6133539bf21a8b9cb6df88fd5232032，公钥047db227d7094ce215c3a0f57e1bcc732551fe351f94249471934567e0f5dc1bf795962b8cccb87a2eb56b29fbe37d614e2f4c3c45b789ae4f1f51f4cb21972ffd）
