### ISSUE TITLE
how to create transaction

### ISSUE THREAD

**Issue by simpleshark** [fractalplatform/fractal#520]
How to craeate transaction using 'https://github.com/fractalplatform/fractal/wiki/%E4%BA%A4%E6%98%93payload%E6%9E%84%E9%80%A0#%E5%88%9B%E5%BB%BA%E8%B4%A6%E5%8F%B7' ? Can you provide me a demo to do it,like requesting the interface or creating local code.

**Comment by JacobDenver007** [comment]
check this 'https://github.com/fractalplatform/fractal/blob/dev/test/multisig/transaction_contract.go', in this test file, you can find how to create account using code, please see function 'generateAccount'
