### ISSUE TITLE
Wrong when executing `make all` under Ubuntu

### ISSUE THREAD

**Issue by yueyun00** [fractalplatform/fractal#530]
~/fractal-0.0.30# make all
······
--- /tmp/gofmt022320232 2019-11-21 15:09:10.482600314 +0800
+++ /tmp/gofmt965464231 2019-11-21 15:09:10.482600314 +0800
@@ -151,7 +151,7 @@
        }
 
accountTxs := &types.AccountTxs{
               Txs:                     txhhpairs,
               Txs: txhhpairs,
                IrreversibleBlockHeight: b.ftservice.engine.CalcBFTIrreversible(),
                EndHeight:               uint64(lastnum),
}

Your marmot has found a problem with the formatting style of the code.
Makefile:38: recipe for target 'check' failed
make: *** [check] Error 1

How can I solve this problem?

**Comment by erickyan86** [comment]
you go version is different of us used, you can `make fmt` then `make all`
