### ISSUE TITLE
How to create a transfer transaction?

### ISSUE THREAD

**Issue by Wangmmx** [fractalplatform/fractal#534]
I built a transaction like this:
```{
    "gasAssetId":0,
    "gasPrice":10000000000000000,
    "actions":[
        {
            "gasLimit":300000,
            "remark":"0xe78e8be69ca8e69ca8e5a49574657374",
            "amount":"0x1",
            "actionType":"0x205",
            "accountName":"wangmenglocal",
            "toAccountName":"wangmenghaha",
            "assetId":0,
            "nonce":1,
            "payload":"0x",
            "payloadDetailInfo":{
                "name":"payload",
                "value":"0x"
            }
        }
    ]
}
```
and then I signed and sent transaction, but got error "Invalid sender" , I guess it failed because wrong signature. I used FTWallet and sent transaction successfully with the same account. How can I get the signature from FTWallet? so that I can check if I did it right, or can you please tell me if I build the transfer body right?

**Comment by erickyan86** [comment]
如果你不想用`ftwallet`来发送交易，而是自己构建交易，你需要把的账户`wangmenglocal `的私钥拿出来，参考[这文件的`sendTransferTx`函数](https://github.com/fractalplatform/fractal/blob/master/test/multisig/transaction_contract.go)，来发送交易

**Comment by Wangmmx** [comment]
> 如果你不想用`ftwallet`来发送交易，而是自己构建交易，你需要把的账户`wangmenglocal `的私钥拿出来，参考[这文件的`sendTransferTx`函数](https://github.com/fractalplatform/fractal/blob/master/test/multisig/transaction_contract.go)，来发送交易

好的我已经构造成功了，感谢回复
